In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import os

In [5]:
current_path = os.getcwd()
parent_path = os.path.dirname(current_path)
data_path = os.path.join(parent_path, 'data')

portfolio = pd.read_csv(data_path + '\\Portfolio_clean.csv')
profile = pd.read_csv(data_path + '\\profile_clean.csv')
transcript = pd.read_csv(data_path + '\\transcript_clean.csv')

In [6]:
portfolio.head()

,reward,social,web,mobile,email,difficulty,duration,offer_type,promo_id
0,10,1,0,1,1,10,7,bogo,ae264e3637204a6fb9bb56bc8210ddfd
1,10,1,1,1,1,10,5,bogo,4d5c57ea9a6940dd891ad53e9dbe8da0
2,0,0,1,1,1,0,4,informational,3f207df678b143eea3cee63160fa8bed
3,5,0,1,1,1,5,7,bogo,9b98b8c7a33c4b65b9aebfe6a799e6d9
4,5,0,1,0,1,20,10,discount,0b1e1539f2cc45b7b9fa7c272da2e1d7

In [7]:
profile.head()

  gender  age                       customer_id became_member_on    income
0    NaN  118  68be06ca386d4c31939f3a4f0e3dd783       12/02/2017       NaN
1      F   55  0610b486422d4921ae7d2bf64640c50b       15/07/2017  112000.0
2    NaN  118  38fe809add3b4fcf9315a9694bb96ff5       12/07/2018       NaN
3      F   75  78afa995795e4d85b5d9ceeca43f5fef       09/05/2017  100000.0
4    NaN  118  a03223e636434f42ac4c3df47e8bac43       04/08/2017       NaN

In [8]:
transcript.head()

,customer_id,event,Record,Record Value,Reward,time
0,e078183556ad4ef3902aa1d963e61314,offer viewed,offer_id,5a8bc65990b245e5a138643cd4eb9837,NaN,558
1,e1469309339d48f299c1431d6de4eaa6,offer viewed,offer_id,5a8bc65990b245e5a138643cd4eb9837,NaN,558
2,e1c5485f813a47a984401e3f8e618d40,offer viewed,offer_id,5a8bc65990b245e5a138643cd4eb9837,NaN,558
3,e89dce9d75634dc5bf1df0a0cea0f316,offer viewed,offer_id,5a8bc65990b245e5a138643cd4eb9837,NaN,558
4,eeed22e7944b4eacb50866dc064a0f1d,offer viewed,offer_id,5a8bc65990b245e5a138643cd4eb9837,NaN,558

In [12]:
merge_df = pd.merge(transcript, portfolio, how = 'left', left_on = 'Record Value', right_on = 'promo_id')
merge_df = pd.merge(merge_df, profile, how = 'left', on = 'customer_id')
merge_df = merge_df.drop(columns = ['Record Value'])

In [18]:
merge_df.shape

(306534, 18)