In [64]:
import pandas as pd
portfolio_df = pd.read_csv('data/portfolio_clean.csv', encoding = 'utf-8')

In [65]:
profile_df = pd.read_csv('data/profile_clean.csv', encoding = 'utf-8')

In [66]:
transcript_df = pd.read_csv('data/transcript_clean.csv', encoding = 'utf-8')

In [67]:
portfolio_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   reward      10 non-null     int64
 1   social      10 non-null     int64
 2   web         10 non-null     int64
 3   mobile      10 non-null     int64
 4   email       10 non-null     int64
 5   difficulty  10 non-null     int64
 6   duration    10 non-null     int64
 7   offer_type  10 non-null     str
 8   promo_id    10 non-null     str
dtypes: int64(7), str(2)
memory usage: 852.0 bytes

In [68]:
portfolio_df.head()

,reward,social,web,mobile,email,difficulty,duration,offer_type,promo_id
0,10,1,0,1,1,10,7,bogo,ae264e3637204a6fb9bb56bc8210ddfd
1,10,1,1,1,1,10,5,bogo,4d5c57ea9a6940dd891ad53e9dbe8da0
2,0,0,1,1,1,0,4,informational,3f207df678b143eea3cee63160fa8bed
3,5,0,1,1,1,5,7,bogo,9b98b8c7a33c4b65b9aebfe6a799e6d9
4,5,0,1,0,1,20,10,discount,0b1e1539f2cc45b7b9fa7c272da2e1d7

In [69]:
transcript_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 306534 entries, 0 to 306533
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   customer_id   306534 non-null  str
 1   event         306534 non-null  str
 2   Record        306534 non-null  str
 3   Record Value  306534 non-null  str
 4   Reward        33579 non-null   float64
 5   time          306534 non-null  int64
dtypes: float64(1), int64(1), str(4)
memory usage: 14.0 MB

In [70]:
transcript_df.head()

,customer_id,event,Record,Record Value,Reward,time
0,e078183556ad4ef3902aa1d963e61314,offer viewed,offer_id,5a8bc65990b245e5a138643cd4eb9837,NaN,558
1,e1469309339d48f299c1431d6de4eaa6,offer viewed,offer_id,5a8bc65990b245e5a138643cd4eb9837,NaN,558
2,e1c5485f813a47a984401e3f8e618d40,offer viewed,offer_id,5a8bc65990b245e5a138643cd4eb9837,NaN,558
3,e89dce9d75634dc5bf1df0a0cea0f316,offer viewed,offer_id,5a8bc65990b245e5a138643cd4eb9837,NaN,558
4,eeed22e7944b4eacb50866dc064a0f1d,offer viewed,offer_id,5a8bc65990b245e5a138643cd4eb9837,NaN,558

In [95]:
profile_df.head(50)

   gender  age                       customer_id became_member_on    income
0     NaN  118  68be06ca386d4c31939f3a4f0e3dd783       12/02/2017       NaN
1       F   55  0610b486422d4921ae7d2bf64640c50b       15/07/2017  112000.0
2     NaN  118  38fe809add3b4fcf9315a9694bb96ff5       12/07/2018       NaN
3       F   75  78afa995795e4d85b5d9ceeca43f5fef       09/05/2017  100000.0
4     NaN  118  a03223e636434f42ac4c3df47e8bac43       04/08/2017       NaN
5       M   68  e2127556f4f64592b11af22de27a7932       26/04/2018   70000.0
6     NaN  118  8ec6ce2a7e7949b1bf142def7d0e0586       25/09/2017       NaN
7     NaN  118  68617ca6246f4fbc85e91a2a49552598       02/10/2017       NaN
8       M   65  389bc3fa690240e798340f5a15918d5c       09/02/2018   53000.0
9     NaN  118  8974fc5686fe429db53ddde067b88302       22/11/2016       NaN
10    NaN  118  c4863c7985cf408faee930f111475da3       24/08/2017       NaN
11    NaN  118  148adfcaa27d485b82f323aaaad036bd       19/09/2015       NaN
12      M   58  2eeac8d8feae4a8cad5a6af0499a211d       11/11/2017   51000.0
13      F   61  aa4862eba776480b8bb9c68455b8c2e1       11/09/2017   57000.0
14      M   26  e12aeaf2d47d42479ea1c4ac3d8286c6       13/02/2014   46000.0
15      F   62  31dda685af34476cad5bc968bdb01c53       11/02/2016   71000.0
16      M   49  62cf5e10845442329191fc246e7bcea3       13/11/2014   52000.0
17    NaN  118  744d603ef08c4f33af5a61c8c7628d1c       01/08/2017       NaN
18      M   57  6445de3b47274c759400cd68131d91b4       31/12/2017   42000.0
19      F   61  a448667f336b42c9a66fc5ffd5d73772       01/05/2018   40000.0
20      F   40  440cf1fd7580490c971d8c651ed962af       04/05/2016   71000.0
21      M   64  4b0da7e80e5945209a1fdddfe813dbe0       09/09/2017  100000.0
22      F   78  c27e0d6ab72c455a8bb66d980963de60       16/06/2017   71000.0
23    NaN  118  2b826eba31074a059d63b0ae8f50b7d5       07/09/2017       NaN
24      M   42  f806632c011441378d4646567f357a21       11/08/2013   69000.0
25      F   56  d058f73bf8674a26a95227db098147b1       28/04/2018   88000.0
26    NaN  118  65aba5c617294649aeb624da249e1ee5       30/03/2017       NaN
27      F   33  c6c9884912c645429f3333f912b55f44       26/09/2017   52000.0
28      F   46  7429a044884842d6862f516c38b1156f       11/09/2017   59000.0
29      M   59  ebe7ef46ea6f4963a7dd49f501b26779       21/01/2015   41000.0
30      M   67  5917d13f6fa04286abdf95f4d5cefb1e       23/08/2014   96000.0
31      O   53  d1ede868e29245ea91818a903fec04c6       16/09/2017   52000.0
32      M   22  1e9420836d554513ab90eba98552d0a9       25/09/2017   70000.0
33      F   96  868317b9be554cb18e50bc68484749a2       17/11/2017   89000.0
34      M   40  f082d80f0aac47a99173ba8ef8fc1909       09/07/2016   33000.0
35      F   69  102e9454054946fda62242d2e176fdce       14/08/2016   57000.0
36    NaN  118  4beeb3ed64dd4898b0edf2f6b67426d3       07/07/2016       NaN
37      M   56  8dabe2142cdf4013a6f4786edf8ab00f       11/05/2014   68000.0
38      F   26  9f30b375d7bd4c62a884ffe7034e09ee       12/08/2017   63000.0
39    NaN  118  25c906289d154b66bf579693f89481c9       13/01/2018       NaN
40      M   75  6e014185620b49bd98749f728747572f       12/11/2015   40000.0
41      F   20  02c083884c7d45b39cc68e1314fec56c       11/07/2016   30000.0
42      M   45  c0d210398dee4a0895b24444a5fcd1d2       07/07/2018   33000.0
43      M   61  8b70ca1f5f5a45bdac2ac2f990b71526       21/11/2017   98000.0
44    NaN  118  5b8f1f0e0930464f93bb55e59b5a04e0       11/11/2014       NaN
45    NaN  118  8be4463721e14d7fa600686bf8c8b2ed       11/05/2017       NaN
46      F   69  8e7c7465e98c43d8a01f51e2b5c29542       18/09/2013   37000.0
47      F   54  57dd18ec5ddc46828afb81ec5977bef2       07/02/2017   80000.0
48      M   39  be8a5d1981a2458d90b255ddc7e0d174       27/05/2014   51000.0
49      F   41  3f89b8f80ebc4f94b7074f28071aa8d4       21/09/2015   41000.0

--------

In [71]:
print("---이벤트 분포---")
print(transcript_df['event'].value_counts())

---이벤트 분포---
event
transaction        138953
offer received      76277
offer viewed        57725
offer completed     33579
Name: count, dtype: int64

In [72]:
transcript_df[transcript_df['event'] == 'transaction'][['event', 'Record Value']]

              event        Record Value
7333    transaction                0.05
7334    transaction                0.05
7335    transaction                0.05
7336    transaction                0.06
7337    transaction                0.08
...             ...                 ...
306279  transaction                3.46
306280  transaction                3.46
306281  transaction                 3.5
306282  transaction  3.5300000000000002
306283  transaction                3.54

[138953 rows x 2 columns]

In [73]:
transcript_df[transcript_df['event'] == 'offer completed'][['event', 'Record']]

                  event    Record
9077    offer completed  offer_id
9083    offer completed  offer_id
9097    offer completed  offer_id
9118    offer completed  offer_id
9119    offer completed  offer_id
...                 ...       ...
306529  offer completed  offer_id
306530  offer completed  offer_id
306531  offer completed  offer_id
306532  offer completed  offer_id
306533  offer completed  offer_id

[33579 rows x 2 columns]

In [79]:
merge_df = pd.merge(
    transcript_df,
    portfolio_df,
    left_on=transcript_df['Record Value'],
    right_on=portfolio_df['promo_id'],
    how='left'
)

if 'key_0' in merge_df.columns :
    merge_df.drop(columns=['key_0'], inplace=True)
merge_df

,customer_id,event,Record,Record Value,Reward,time,reward,social,web,mobile,email,difficulty,duration,offer_type,promo_id
0,e078183556ad4ef3902aa1d963e61314,offer viewed,offer_id,5a8bc65990b245e5a138643cd4eb9837,NaN,558,0.0,1.0,0.0,1.0,1.0,0.0,3.0,informational,5a8bc65990b245e5a138643cd4eb9837
1,e1469309339d48f299c1431d6de4eaa6,offer viewed,offer_id,5a8bc65990b245e5a138643cd4eb9837,NaN,558,0.0,1.0,0.0,1.0,1.0,0.0,3.0,informational,5a8bc65990b245e5a138643cd4eb9837
2,e1c5485f813a47a984401e3f8e618d40,offer viewed,offer_id,5a8bc65990b245e5a138643cd4eb9837,NaN,558,0.0,1.0,0.0,1.0,1.0,0.0,3.0,informational,5a8bc65990b245e5a138643cd4eb9837
3,e89dce9d75634dc5bf1df0a0cea0f316,offer viewed,offer_id,5a8bc65990b245e5a138643cd4eb9837,NaN,558,0.0,1.0,0.0,1.0,1.0,0.0,3.0,informational,5a8bc65990b245e5a138643cd4eb9837
4,eeed22e7944b4eacb50866dc064a0f1d,offer viewed,offer_id,5a8bc65990b245e5a138643cd4eb9837,NaN,558,0.0,1.0,0.0,1.0,1.0,0.0,3.0,informational,5a8bc65990b245e5a138643cd4eb9837
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306529,303bff336e8449d6a2fb84ed67d48602,offer completed,offer_id,9b98b8c7a33c4b65b9aebfe6a799e6d9,5.0,486,5.0,0.0,1.0,1.0,1.0,5.0,7.0,bogo,9b98b8c7a33c4b65b9aebfe6a799e6d9
306530,30aad290db6a4c198edf5fd4c00c3553,offer completed,offer_id,9b98b8c7a33c4b65b9aebfe6a799e6d9,5.0,486,5.0,0.0,1.0,1.0,1.0,5.0,7.0,bogo,9b98b8c7a33c4b65b9aebfe6a799e6d9
306531,42b57a678bda41d88dd6adfa2e5f8d5d,offer completed,offer_id,9b98b8c7a33c4b65b9aebfe6a799e6d9,5.0,486,5.0,0.0,1.0,1.0,1.0,5.0,7.0,bogo,9b98b8c7a33c4b65b9aebfe6a799e6d9
306532,48d781b45b1f454b9d19f5144864eebc,offer completed,offer_id,9b98b8c7a33c4b65b9aebfe6a799e6d9,5.0,486,5.0,0.0,1.0,1.0,1.0,5.0,7.0,bogo,9b98b8c7a33c4b65b9aebfe6a799e6d9
306533,4bffdccc6681472b9b61da924657de14,offer completed,offer_id,9b98b8c7a33c4b65b9aebfe6a799e6d9,5.0,486,5.0,0.0,1.0,1.0,1.0,5.0,7.0,bogo,9b98b8c7a33c4b65b9aebfe6a799e6d9

In [85]:
offer_df = merge_df[merge_df['Record'] == 'offer_id'].copy()
offer_df = offer_df.sort_values(['customer_id', 'promo_id', 'time'])

In [86]:
offer_df['sequence'] = offer_df.groupby(['customer_id', 'promo_id'])['time'].rank(method='first')

In [90]:
sequence = offer_df.pivot_table(
    index=['customer_id', 'promo_id'],
    columns='event',
    values='time',
    aggfunc='min'
).reset_index()

column_order = ['customer_id', 'promo_id', 'offer received', 'offer viewed', 'offer completed']

existing_cols = [col for col in column_order if col in sequence.columns]
sequence = sequence.reindex(columns=existing_cols)
sequence

event,customer_id,promo_id,offer received,offer viewed,offer completed
0,0009655768c64bdeb2e877511632db8f,2906b810c7d4411798c6938adc9daaa5,576.0,NaN,576.0
1,0009655768c64bdeb2e877511632db8f,3f207df678b143eea3cee63160fa8bed,336.0,372.0,NaN
2,0009655768c64bdeb2e877511632db8f,5a8bc65990b245e5a138643cd4eb9837,168.0,192.0,NaN
3,0009655768c64bdeb2e877511632db8f,f19421c1d4aa40978ebb69ca19b0e20d,408.0,456.0,414.0
4,0009655768c64bdeb2e877511632db8f,fafdcd668e3743c1bb461111dcafc2a4,504.0,540.0,528.0
...,...,...,...,...,...
63283,fffad4f4828548d1b5583907f2e9906b,f19421c1d4aa40978ebb69ca19b0e20d,0.0,6.0,36.0
63284,ffff82501cea40309d5fdd7edcca4a07,0b1e1539f2cc45b7b9fa7c272da2e1d7,168.0,174.0,198.0
63285,ffff82501cea40309d5fdd7edcca4a07,2906b810c7d4411798c6938adc9daaa5,336.0,354.0,384.0
63286,ffff82501cea40309d5fdd7edcca4a07,9b98b8c7a33c4b65b9aebfe6a799e6d9,504.0,534.0,504.0
63287,ffff82501cea40309d5fdd7edcca4a07,fafdcd668e3743c1bb461111dcafc2a4,0.0,6.0,60.0

In [91]:
merge_df['Reward'].value_counts()

Reward
5.0     12070
2.0      9334
10.0     7019
3.0      5156
Name: count, dtype: int64

In [96]:
merge_df['duration'].value_counts()

duration
7.0     70170
5.0     37353
10.0    33992
3.0     14305
4.0     11761
Name: count, dtype: int64

In [98]:
merge_df[merge_df['customer_id'] == '1f6ad0a8def240b3ad633f83032dedd8']

,customer_id,event,Record,Record Value,Reward,time,reward,social,web,mobile,email,difficulty,duration,offer_type,promo_id
10694,1f6ad0a8def240b3ad633f83032dedd8,transaction,amount,2.94,NaN,480,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12319,1f6ad0a8def240b3ad633f83032dedd8,offer viewed,offer_id,ae264e3637204a6fb9bb56bc8210ddfd,NaN,588,10.0,1.0,0.0,1.0,1.0,10.0,7.0,bogo,ae264e3637204a6fb9bb56bc8210ddfd
12916,1f6ad0a8def240b3ad633f83032dedd8,transaction,amount,3.26,NaN,492,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49147,1f6ad0a8def240b3ad633f83032dedd8,transaction,amount,0.88,NaN,672,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49419,1f6ad0a8def240b3ad633f83032dedd8,transaction,amount,72.23,NaN,504,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52095,1f6ad0a8def240b3ad633f83032dedd8,transaction,amount,6.15,NaN,558,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65063,1f6ad0a8def240b3ad633f83032dedd8,transaction,amount,2.61,NaN,606,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70023,1f6ad0a8def240b3ad633f83032dedd8,transaction,amount,2.19,NaN,624,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91463,1f6ad0a8def240b3ad633f83032dedd8,transaction,amount,5.85,NaN,594,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100387,1f6ad0a8def240b3ad633f83032dedd8,transaction,amount,7.33,NaN,60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111996,1f6ad0a8def240b3ad633f83032dedd8,offer completed,offer_id,4d5c57ea9a6940dd891ad53e9dbe8da0,10.0,504,10.0,1.0,1.0,1.0,1.0,10.0,5.0,bogo,4d5c57ea9a6940dd891ad53e9dbe8da0
111997,1f6ad0a8def240b3ad633f83032dedd8,offer completed,offer_id,4d5c57ea9a6940dd891ad53e9dbe8da0,10.0,504,10.0,1.0,1.0,1.0,1.0,10.0,5.0,bogo,4d5c57ea9a6940dd891ad53e9dbe8da0
125809,1f6ad0a8def240b3ad633f83032dedd8,offer received,offer_id,9b98b8c7a33c4b65b9aebfe6a799e6d9,NaN,336,5.0,0.0,1.0,1.0,1.0,5.0,7.0,bogo,9b98b8c7a33c4b65b9aebfe6a799e6d9
132249,1f6ad0a8def240b3ad633f83032dedd8,offer received,offer_id,ae264e3637204a6fb9bb56bc8210ddfd,NaN,168,10.0,1.0,0.0,1.0,1.0,10.0,7.0,bogo,ae264e3637204a6fb9bb56bc8210ddfd
153259,1f6ad0a8def240b3ad633f83032dedd8,offer viewed,offer_id,4d5c57ea9a6940dd891ad53e9dbe8da0,NaN,540,10.0,1.0,1.0,1.0,1.0,10.0,5.0,bogo,4d5c57ea9a6940dd891ad53e9dbe8da0
165624,1f6ad0a8def240b3ad633f83032dedd8,transaction,amount,5.68,NaN,450,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180396,1f6ad0a8def240b3ad633f83032dedd8,offer received,offer_id,4d5c57ea9a6940dd891ad53e9dbe8da0,NaN,504,10.0,1.0,1.0,1.0,1.0,10.0,5.0,bogo,4d5c57ea9a6940dd891ad53e9dbe8da0
183443,1f6ad0a8def240b3ad633f83032dedd8,transaction,amount,4.34,NaN,396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189739,1f6ad0a8def240b3ad633f83032dedd8,offer received,offer_id,ae264e3637204a6fb9bb56bc8210ddfd,NaN,576,10.0,1.0,0.0,1.0,1.0,10.0,7.0,bogo,ae264e3637204a6fb9bb56bc8210ddfd
192917,1f6ad0a8def240b3ad633f83032dedd8,transaction,amount,3.11,NaN,468,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
202529,1f6ad0a8def240b3ad633f83032dedd8,transaction,amount,8.8,NaN,222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204029,1f6ad0a8def240b3ad633f83032dedd8,transaction,amount,1.92,NaN,234,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
212595,1f6ad0a8def240b3ad633f83032dedd8,offer viewed,offer_id,4d5c57ea9a6940dd891ad53e9dbe8da0,NaN,432,10.0,1.0,1.0,1.0,1.0,10.0,5.0,bogo,4d5c57ea9a6940dd891ad53e9dbe8da0
243072,1f6ad0a8def240b3ad633f83032dedd8,transaction,amount,4.17,NaN,168,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
249933,1f6ad0a8def240b3ad633f83032dedd8,transaction,amount,0.36,NaN,210,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265443,1f6ad0a8def240b3ad633f83032dedd8,offer received,offer_id,4d5c57ea9a6940dd891ad53e9dbe8da0,NaN,408,10.0,1.0,1.0,1.0,1.0,10.0,5.0,bogo,4d5c57ea9a6940dd891ad53e9dbe8da0
273954,1f6ad0a8def240b3ad633f83032dedd8,offer viewed,offer_id,ae264e3637204a6fb9bb56bc8210ddfd,NaN,168,10.0,1.0,0.0,1.0,1.0,10.0,7.0,bogo,ae264e3637204a6fb9bb56bc8210ddfd
275704,1f6ad0a8def240b3ad633f83032dedd8,offer completed,offer_id,9b98b8c7a33c4b65b9aebfe6a799e6d9,5.0,450,5.0,0.0,1.0,1.0,1.0,5.0,7.0,bogo,9b98b8c7a33c4b65b9aebfe6a799e6d9
298786,1f6ad0a8def240b3ad633f83032dedd8,transaction,amount,4.36,NaN,300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
299703,1f6ad0a8def240b3ad633f83032dedd8,transaction,amount,5.44,NaN,306,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
302003,1f6ad0a8def240b3ad633f83032dedd8,transaction,amount,2.49,NaN,324,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN